// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2LtWOZNCQJ9gPzX6MYqmR9blwyBCEQk',
    appId: '1:672369546081:web:159d1b3ed9373ebe88ab20',
    messagingSenderId: '672369546081',
    projectId: 'mentimeterclone',
    authDomain: 'mentimeterclone.firebaseapp.com',
    databaseURL: 'https://mentimeterclone-default-rtdb.firebaseio.com',
    storageBucket: 'mentimeterclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOrylYRwdQCWjSbxXoeIRV6U9akEmt8Uw',
    appId: '1:672369546081:android:2821334ff3fa078c88ab20',
    messagingSenderId: '672369546081',
    projectId: 'mentimeterclone',
    databaseURL: 'https://mentimeterclone-default-rtdb.firebaseio.com',
    storageBucket: 'mentimeterclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwPimdcGSTKXEnfvYFqj3PBkbZEV5Tc8',
    appId: '1:672369546081:ios:2407d678e37f874488ab20',
    messagingSenderId: '672369546081',
    projectId: 'mentimeterclone',
    databaseURL: 'https://mentimeterclone-default-rtdb.firebaseio.com',
    storageBucket: 'mentimeterclone.appspot.com',
    iosClientId: '672369546081-thhkdv4o7f3g1hpgpof9804rvat2mdgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentimeterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwPimdcGSTKXEnfvYFqj3PBkbZEV5Tc8',
    appId: '1:672369546081:ios:2407d678e37f874488ab20',
    messagingSenderId: '672369546081',
    projectId: 'mentimeterclone',
    databaseURL: 'https://mentimeterclone-default-rtdb.firebaseio.com',
    storageBucket: 'mentimeterclone.appspot.com',
    iosClientId: '672369546081-thhkdv4o7f3g1hpgpof9804rvat2mdgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentimeterClone',
  );
}
